title: handyman
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7085106
  brandStrength: 0.2223761097993702
  lightness: 0.4723404
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  rhythmicContrast: 0.6021277
typography_spectrum: 0.3276596
description: services
layout_spectrum: 0.3
name: malcolmvincent
